### PR TITLE
Extract Cadence templates

### LINKED ISSUE #185: Use new Cadence account key API
**Is your feature request related to a problem? Please describe.**

Cadence has a new API for account keys: https://docs.onflow.org/cadence/language/accounts/#account-key-api

It'd be great if the Go SDK started using it!

**Describe the solution you'd like**

The transaction templates in `templates` should be upgraded to use the new Cadence account key API.

**Describe alternatives you've considered**

None! We can't pass up on the sweet new API. 😄

### PR DESCRIPTION
**Pull request by sideninja**
Closes #185 #224 

## Description
This PR extracts Cadence [templates to a separate repo for SDKs](https://github.com/onflow/sdks/tree/main/templates/cadence). It then creates a module that embeds those templates and references them from SDK. More examples were added for templates.

______

For contributor use:

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Code follows the [standards mentioned here](https://github.com/onflow/flow-go-sdk/blob/master/CONTRIBUTING.md#styleguides).
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Comment by sideninja** [comment]
I want to get this merged because it's blocking secure Cadence testing as seen here https://github.com/onflow/flow-go-sdk/pull/276#issuecomment-1104077881 
Help would be appreciated from code owners cc @janezpodhostnik @turbolent

**Review by janezpodhostnik — APPROVED** [review]
This looks good to me, but can we rename `[remove-account-key.cdc](https://github.com/onflow/sdks/blob/main/templates/cadence/remove-account-key.cdc)` to revoke-account-key.cdc

**Comment by sideninja** [comment]
> This looks good to me, but can we rename `[remove-account-key.cdc](https://github.com/onflow/sdks/blob/main/templates/cadence/remove-account-key.cdc)` to revoke-account-key.cdc

Good point.

**Comment by sideninja** [comment]
> This looks good to me, but can we rename `[remove-account-key.cdc](https://github.com/onflow/sdks/blob/main/templates/cadence/remove-account-key.cdc)` to revoke-account-key.cdc

Fixed

**Pull request merged**
