### PR TITLE
update SDK usage examples

### PR DESCRIPTION
**Pull request by nozim**
## Description

Update examples folder with running examples.
______

For contributor use:

- [x] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Code follows the [standards mentioned here](https://github.com/onflow/flow-go-sdk/blob/master/CONTRIBUTING.md#styleguides).
- [ ] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

**Comment by sideninja** [comment]
I believe you forgot to mod tidy @nozim

**Comment by nozim** [comment]
@sideninja updated, thanks 😊

**Comment by nozim** [comment]
yes, also there is another failing example. Will fix in a bit. Thanks

**Comment by sideninja** [comment]
@chasefleming mind reviewing?

**Comment by chasefleming** [comment]
@nozim rerunning

**Comment by nozim** [comment]
@chasefleming mock file access/http/mock_handler.go seems to be updated after it's pushed, Can you please check.

**Comment by nozim** [comment]
@chasefleming awesome. thanks for help.

**Comment by nozim** [comment]
@chasefleming @sideninja kindly help to review. This should be last one :)

**Comment by nozim** [comment]
@nvdtf @chasefleming kindly help to re-review and merge if all good 🙏

**Review by chasefleming — COMMENTED** [review]
@nozim Is there an issue to link to? It's a little unclear about what I should be reviewing for.

**Comment by nozim** [comment]
@chasefleming there is no particular issue for this PR. It's rather update of all the examples because they were outdated and did not compile.

**Review by chasefleming — APPROVED** [review]

**Comment by nozim** [comment]
@sideninja @nvdtf kindly help to review and merge if there is no other comments. Thanks

**Pull request merged**
