### PR TITLE
Fix cloudkms signer is not threadsafe

### PR DESCRIPTION
**Pull request by judezhu**
Closes: #260 

## Description

Create a new `hasher` in cloudkms signer, when signing flow transactions.

______

For contributor use:

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Code follows the [standards mentioned here](https://github.com/onflow/flow-go-sdk/blob/master/CONTRIBUTING.md#styleguides).
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

**Review by turbolent — APPROVED** [review]
Thank you!

Alternatively we could put a mutex around it, or maybe just document that the API is not thread-safe and requires users to handle it. I'm OK with this solution

**Comment by judezhu** [comment]
> Thank you!
> 
> Alternatively we could put a mutex around it, or maybe just document that the API is not thread-safe and requires users to handle it. I'm OK with this solution

Thanks for the quick feedback! We noticed this issue when we were trying to sign/send multiple flow transactions in parallel. We ended up with a workaround to get it working. But it will be much easier if we can support this in the upstream lib.

**Review by sideninja — APPROVED** [review]
Thank you, I think this makes sense, since moving the hash calculation is the only part making it unsafe, I don't believe there is much overhead doing so.

**Comment by tarakby** [comment]
- it seems to me that the updated code is double-hashing the message to sign (once with the hasher + once with KMS). Did I miss something?
- Since there are still calls to hash on KMS (the same call that seems to cause the errors in the first place), I'm wondering if the issue is really solved from your tests?
- I didn't audit this code before and this was not added by this PR, but ideally the call to sign on KMS should include the hashing (this means the [request](https://github.com/judezhu/flow-go-sdk/blob/c5742b71d6a314193cba868f63f7f9b65844ab05/crypto/cloudkms/signer.go#L74) to sign should include the message and not the digest). Hopefully that would solve the thread issue too.

**Comment by psiemens** [comment]
👍 to @tarakby's comment.

Cloud KMS actually allows you to either pass either un-hashed `data` or a pre-hashed `digest` (but not both), so I don't think this will produce the wrong signature. (ref: https://cloud.google.com/kms/docs/create-validate-signatures#data_versus_digest).

But I think we can just pass `data` and then just remove the hasher instance altogether.

**Comment by tarakby** [comment]
> Cloud KMS actually allows you to either pass either un-hashed data or a pre-hashed digest (but not both), so I don't think this will produce the wrong signature

Thanks @psiemens, yes the kms interface allows to include either data or digest in the signing request. The original code looks correct to me, but I might be still missing something with the code updated after this PR: 
https://github.com/onflow/flow-go-sdk/blob/8fc9b5e084cf056ec09adec8004bfe33449dcc3b/crypto/cloudkms/signer.go#L63-L77

Line 67 computes the first hash with the hasher, line 69 computes the hash of the hash with KMS, line 76 includes the hash of the hash to be signed as a digest. Unless the verification is also double hashing, I guess this signature won't be valid.

**Comment by tarakby** [comment]
In my comment I mainly mentioned 2 points:
 1. [correctness] double hashing should be avoided, otherwise it won't be validated by a correct verification.
 2. [best practice] if an HSM is used, it is recommended to delegate all cryptographic computations to it including hashing. Although hashing only deals with public data, it can lead to attacks in the context of signatures. An HSM is used when a the external environment isn't 100% trusted, so better to include hashing in the trusted environment too (in some designs that's not possible and that's why the kms API offers signing the digest).
 
 I'll open a PR to update 1 (pending your confirmation that I didn't misread the code) and 2.

**Comment by psiemens** [comment]
@tarakby The call to `makeDigest` doesn't actually compute a hash, it just prepares the hash data structure required by KMS. So I don't think there is any double hashing.

But I agree with your point about delegating all cryptographic computations to KMS.

https://github.com/onflow/flow-go-sdk/blob/8fc9b5e084cf056ec09adec8004bfe33449dcc3b/crypto/cloudkms/signer.go#L92-L101

**Comment by psiemens** [comment]
@tarakby A PR to fix point 2 would be great!

**Comment by judezhu** [comment]
> double hashing should be avoided, otherwise it won't be validated by a correct verification.

I don't get the double hashing issue here. The change we made in this PR is not adding one more hash. Basically, we just replace the shared `hasher`, with a local `hasher` initialized in the `Sign` method.

**Comment by tarakby** [comment]
> The call to makeDigest doesn't actually compute a hash, it just prepares the hash data structure required by KMS

My bad, I thought that function was computing a hash. Sorry @psiemens and @judezhu and thanks both for your clarifications!

**Pull request merged**
