### PR TITLE
updating Cadence to v0.23.3

### PR DESCRIPTION
**Pull request by vishalchangrani**
Huobi flagged that the `flow-go-sdk` is still using the older version of Cbor. 

I updated the Cadence version (since [mainnet is also already running](https://github.com/onflow/flow-go/blob/v0.25/go.mod#L61) on the newer Cadence version `v0.23.3`) which in-turn updated Cbor.

**However**, I still didn't get to cbor v.2.4.0.

_I noticed Candence [latest release](https://github.com/onflow/cadence/blob/v0.23.4/go.mod#L9) is also not using cbor v.2.4.0._

Lex from Huobi (on the Telegram channel `Flow <> Huobi`) - 
> In flow-go-sdk, the current version of cbor is v2.2.1-0.20210927235116-3d6d5d1de29b, which currently affects the running of our program. Can you upgrade the version of cbor to v2.4.0?

## Description

______

For contributor use:

- [ ] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-go-sdk/blob/master/CONTRIBUTING.md#styleguides).
- [ ] Updated relevant documentation 
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

**Comment by sideninja** [comment]
@vishalchangrani do you ned my help with this or is your change working? I plan to make a bigger release of Go SDK soon and also planned to update all deps to the latest versions.

**Comment by vishalchangrani** [comment]
> @vishalchangrani do you ned my help with this or is your change working? I plan to make a bigger release of Go SDK soon and also planned to update all deps to the latest versions.

Hi @sideninja - is there anything I need to do to test this change? I have never made a `flow-go-sdk` release so not sure what goes into it.

**Comment by sideninja** [comment]
> > @vishalchangrani do you ned my help with this or is your change working? I plan to make a bigger release of Go SDK soon and also planned to update all deps to the latest versions.
> 
> Hi @sideninja - is there anything I need to do to test this change? I have never made a `flow-go-sdk` release so not sure what goes into it.

Do I understand you try to update Cbor but you couldn't?

**Comment by vishalchangrani** [comment]
> > > @vishalchangrani do you ned my help with this or is your change working? I plan to make a bigger release of Go SDK soon and also planned to update all deps to the latest versions.
> > 
> > 
> > Hi @sideninja - is there anything I need to do to test this change? I have never made a `flow-go-sdk` release so not sure what goes into it.
> 
> Do I understand you try to update Cbor but you couldn't?

Yup - so, I updated the Cadence version but it does not include the latest cbor. Not that this [PR](https://github.com/onflow/cadence/pull/1596) has been merged into Cadence, when the Cadence release happens, I will update the cadence dependency to that release which should then pull the latest cbor :)

**Comment by vishalchangrani** [comment]
closing in favour of https://github.com/onflow/flow-go-sdk/pull/280

**Pull request closed without merging**
