### PR TITLE
[BUGFIX] fix readme

### PR DESCRIPTION
**Pull request by qq976739120**
It looks like you haven't updated it in a long time.I've only fixed part of the problem,And make it more in line with the GO specification.I would like to work for this SDK for a long time.

### CODE REVIEW

**Review by psiemens — COMMENTED** [review]
These are great suggestions, thank you @qq976739120!

I originally wrote the examples as partial Go programs in order to keep them short. Seeing them now, I agree that it'd be better if they would actually compile. 

Do you think it would make more sense to remove the code snippets from the README and instead just link directly to the examples in the `/examples` directory?

**Comment by qq976739120** [comment]
> These are great suggestions, thank you @qq976739120!
> 
> I originally wrote the examples as partial Go programs in order to keep them short. Seeing them now, I agree that it'd be better if they would actually compile.
> 
> Do you think it would make more sense to remove the code snippets from the README and instead just link directly to the examples in the `/examples` directory?
This seems like a big change.I looked carefully at the code  in the `/examples` directory,I think I have some optimizations.

**Comment by qq976739120** [comment]
> Do you think it would make more sense to remove the code snippets from the README and instead just link directly to the examples in the `/examples` directory?

This seems like a big change.I looked carefully at the code in the /examples directory,I think I have some optimizations.

**Comment by psiemens** [comment]
> I looked carefully at the code in the /examples directory, I think I have some optimizations.

I agree. Is that something you'd want to work on? We're very open to contributions 😄

**Comment by qq976739120** [comment]
> I agree. Is that something you'd want to work on? We're very open to contributions 😄

Is there a group of developers to communicate with? More detailed communication is needed. I don't have it on the official website

**Comment by psiemens** [comment]
@qq976739120 You can find us in our Discord server: https://discord.gg/flow

We mostly talk about this project in the `#flow-go-sdk` channel. Happy to chat there!

**Pull request closed without merging**
